services:
  voicevox:
    image: "voicevox/voicevox_engine:cpu-ubuntu24.04-latest"
    ports:
      - "50021:50021"
    restart: always

  main:
    build: .
    command: python main.py
    volumes:
      - './log:/app/log'
    restart: always
    depends_on:
      - voicevox
