services:
  voicevox:
    # image: "voicevox/voicevox_engine:nvidia-ubuntu20.04-latest"
    image: "voicevox/voicevox_engine:cpu-ubuntu20.04-latest"
    ports:
      - "50021:50021"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  main:
    build: .
    command: python main.py
    volumes:
      - './log:/app/log'
    depends_on:
      - voicevox
